import numpy as np
from numpy import zeros, array
from numpy.linalg import norm
import matplotlib.pyplot as plt

# You never need to unroll vector of matrix operation:
# - x+y is the simple way to add vectors
# - A @ B to multiply matrices or vectors, including inner products
# - Most linear algebraic operations are provided in numpy, or numpy.linalg
#   https://numpy.org/doc/stable/reference/routines.linalg.html
# - coefficient-wise operation are also provided, such as np.round(x) to round each coordinate
# - Doing so will be simpler, more readable, and much faster than writing a for loop

#   ^
#  /|\    When implementing, it is more common to use *row* notations (and faster...)
# / | \   Do so. And beware on which side you are multiplying vectors and matrices !
#/__*__\

# The exercises comprises of function to be implemented (except Exercise 0):
# Replace the keyword "pass" with your implementation of the desired function


############ 
# Exercise 0
# Read the following utility function and test to get use to python an numpy
# syntax and objects
############

# By default, arrays are float in numpy. The following is a shortener to
# construct integer arrays.
def iarray(x):
	return array(x, dtype=int)

def in_lattice(B, v):
	"""
    Check whether a vector `v` belongs to the lattice generated by the basis `B`,
	up to a small numerical tolerance.

    :param B: A square (n x n) NumPy array representing a lattice basis.
    :type B: numpy.ndarray
    :param v: A NumPy array representing the target vector to test.
    :type v: numpy.ndarray

    :return: True if `v` lies in the lattice generated by `B` (within numerical tolerance), False otherwise.
    :rtype: bool

    :notes: Make use of numpy.linalg function solve and numpy functions round and allclose.
    """

	# Write v in base B as x: x = B^T * v
	x = np.linalg.solve(B.transpose(), v)

	# Round to make it an integer vector. If v this indeed a lattice point,
	# this step should merely fix floating-point numerical errors.
	xr = np.round(x)

	# Check equality up to some small tolerance
	return np.allclose(x, xr)

############
# Exercise 1
# Implement the Simple Rounding Algorithm 
############

def simple_rounding(B, t):
	"""
    Return a lattice vector close to the target vector `t`, using the Simple Rounding algorithm.

    :param B: A square (n x n) NumPy array representing a lattice basis.
    :type B: numpy.ndarray
    :param t: A NumPy array representing the target vector to approximate with a lattice point.
    :type t: numpy.ndarray

    :return: A lattice vector in the lattice generated by `B` that is close to `t`.
    :rtype: numpy.ndarray

    :notes: Make use of numpy.linalg function solve and numpy function round.
    """

	x = np.linalg.solve(B.transpose(), t)
	xr = np.round(x)

	return xr @ B


############
# Exercise 2
# Implement Gram-Schmidt Orthogonalization Algorihm
# Use a projection Subroutine
############

def orth_proj(x, y):
	""" Returns the orthogonal projection of vector x orthognally to vector y,
	namely: x - <x,y>/<y,y> y"""
	
	return x - (x @ y) / (y @ y) * y

def Gram_Schmidt_orth(B):
	"""
    Perform Gram-Schmidt orthogonalization on the rows of a matrix `B`.

    :param B: A square (n x n) NumPy array representing the basis vectors of a lattice.
              Each row of `B` is considered a basis vector.
    :type B: numpy.ndarray

    :return: A NumPy array of the same shape as `B`, containing the orthogonalized basis vectors.
             The i-th row of the output is the orthogonal to the span of previous basis vectors.
    :rtype: numpy.ndarray

    :notes: 
        
    """

	# Get the dimension of the square basis
	n,_ = B.shape

	# Makes a copy of B, but change the type to float
	Bs = array(B, dtype=float)

	for i in range(n):
		for j in range(i):
			Bs[i] = orth_proj(Bs[i], Bs[j])

	return Bs


############
# Exercise 3
# Implement The Nearest-Plane Rounding Algorithm (Babai)
############

def nearest_plane(B, Bs, t):
	"""
    Apply Babai's Nearest Plane Algorithm to approximate a target vector `t`
    with a nearby lattice point from the lattice generated by basis `B`.

    :param B: A NumPy array of shape (n, d) representing the lattice basis.
              Each row of `B` is a basis vector.
    :type B: numpy.ndarray
    :param Bs: A NumPy array of shape (n, d) containing the Gram-Schmidt orthogonalization
               of the basis `B`.
    :type Bs: numpy.ndarray
    :param t: A NumPy array of shape (d,) representing the target vector to approximate.
    :type t: numpy.ndarray

    :return: A lattice vector (as a NumPy array) in the lattice generated by `B`,
             which is close to the target `t`.
    :rtype: numpy.ndarray

    :notes: Make use of numpy round() function and the built-in int() conversion.
    """

	n,d = B.shape

	# copy t, to avoid modying the value of the function caller
	e = np.copy(t)
	v = zeros(d, dtype=int)

	for i in reversed(range(n)):
		k = int(np.round((e @ Bs[i]) / (Bs[i]@Bs[i])))
		e -= k * B[i]
		v += k * B[i]

	return v

############
# Exercise 4
# Compare the distribution of Euclidean norm of points in the fundamental
# domains P(B) and P(Bs) given a basis B, by plotting their histograms.
# The plotting function is provided.
#
# There is no need to actually run simple_rounding nor nearest_plane.
############

def plot_two_hist(data_SR, data_NP, n, save=False):
	"""Take is input two lists and plot two histograms"""
	
	_, bins, _ = plt.hist(data_SR, bins=100, density=True, label="Simple Rounding")
	_ = plt.hist(data_NP, bins=bins, alpha=0.5, density=True, label="Nearest Plane")
	
	plt.title("Length of random points in Fundamental Parallelepiped \n Basis dimension: %d"%n)
	plt.legend()
	
	if save:
		plt.savefig("ParallelepipedDistDim%d.png"%n)
	else:
		plt.show()
	
	plt.clf()
	plt.close()

def compare_norm_distrib(B, num_samples):

	"""
    Compare the distribution of vector norms in the fundamental domains of a basis `B`
    and its Gram-Schmidt orthogonalization `Bs`, by generating and plotting histograms.

    :param B: A NumPy array of shape (n, n) representing a lattice basis.
              Each row is treated as a basis vector.
    :type B: numpy.ndarray
    :param num_samples: The number of random samples to generate from each distribution.
    :type num_samples: int

    :notes: Make use of numpy.linalg function norm and numpy.random function rand
    """

	n, _ = B.shape

	# Calculate Gram-Schmidt orthogonalization of basis B
	Bs = Gram_Schmidt_orth(B)

	# Calculate num_samples samples from the distribution of Euclidean norm of points in the fundamental domain P(B)
	data_SR = [np.linalg.norm((np.random.rand(n) - .5) @ B) for x in range(num_samples)]

	# Calculate num_samples samples from the distribution of Euclidean norm of points in the fundamental domain P(Bs)
	data_NP = [np.linalg.norm((np.random.rand(n) - .5) @ Bs) for x in range(num_samples)]
	
	# Plot the distributions
	plot_two_hist(data_SR, data_NP, n)

